import "fake-indexeddb/auto";
import { describe, it, beforeEach, after } from "node:test";
import assert from "node:assert/strict";
import { db } from "../src/scripts/shared/db.ts";
import { RecordStore } from "../src/scripts/shared/recordStore.ts";
import { Repository } from "../src/scripts/shared/repository.ts";

interface Row {
    id: string;
    title: string;
    unread: boolean;
}

const repository = () =>
    new Repository<Row>(new RecordStore<Row>({ title: "", unread: true }), "items");

/** The writes are fire-and-forget, so the assertions have to let them land. */
const settled = () => new Promise((resolve) => setTimeout(resolve, 0));

beforeEach(async () => {
    await Promise.all(db.tables.map((table) => table.clear()));
});

after(() => db.close());

describe("Repository", () => {
    it("does not persist static toolbar definitions", () => {
        assert.equal(
            db.tables.some((table) => table.name === "toolbars"),
            false
        );
    });

    /**
     * `data-create` answers with the id straight away, long before the write
     * lands, so the id cannot be generated by the database.
     */
    it("assigns an id synchronously", () => {
        const record = repository().create({ title: "One" });
        assert.ok(record.id);
    });

    it("keeps an explicit id", () => {
        const record = repository().create({ id: "given", title: "One" });
        assert.equal(record.id, "given");
    });

    it("writes a created record", async () => {
        const repo = repository();
        const record = repo.create({ title: "One" });
        await settled();

        assert.equal((await db.table("items").get(record.id)).title, "One");
    });

    it("writes an update and keeps the store in step", async () => {
        const repo = repository();
        const record = repo.create({ title: "One" });
        await settled();

        repo.update([record.id], { title: "Two" });
        await settled();

        assert.equal(repo.store.get(record.id).title, "Two");
        assert.equal((await db.table("items").get(record.id)).title, "Two");
    });

    it("deletes from both the store and the table", async () => {
        const repo = repository();
        const record = repo.create({ title: "One" });
        await settled();

        repo.remove([record.id]);
        await settled();

        assert.equal(repo.store.get(record.id), undefined);
        assert.equal(await db.table("items").get(record.id), undefined);
    });

    it("loads what was written, replacing whatever the store held", async () => {
        const first = repository();
        first.create({ id: "a", title: "One" });
        await settled();

        const second = repository();
        second.store.add([{ id: "ghost", title: "Stale", unread: true }]);
        await second.load();

        assert.deepEqual(
            second.store.all().map((record) => record.id),
            ["a"]
        );
    });

    it("merges a batch and writes only what it touched", async () => {
        const repo = repository();
        repo.create({ id: "a", title: "One" });
        await settled();

        const touched = repo.put([
            { id: "a", title: "One" },
            { id: "b", title: "Two" },
        ]);
        await settled();

        assert.deepEqual(
            touched.map((record) => record.id),
            ["b"]
        );
        assert.equal((await db.table("items").get("b")).title, "Two");
    });
});
